### ISSUE TITLE
Password undefined when attempting to open WebUI

### ISSUE THREAD

**Issue by nightops** [hassio-addons/addon-control-panel#2]
# Problem/Motivation

> Unable to use the control panel

## Expected behavior

> Able to use the control panel

## Actual behavior

> keeps prompting for the URL

## Steps to reproduce

> Fresh install, enabled, updated config YAML to:

http:
  base_url: http://hassio.local:8123
  api_password: !secret api_password
  cors_allowed_origins:
    - http://hassio.local:7080

(api_password is defined in secrets.yaml)

## Proposed changes
> I probably don't have something configured correctly, so probably no changes are required.

**Comment by nightops** [comment]
From ha LOG:
2018-04-27 16:41:51 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 10.1.100.98
2018-04-27 16:41:58 ERROR (MainThread) [homeassistant.components.websocket_api] WS 1864911856: Message incorrectly formatted: extra keys not allowed @ data['event_type']. Got 'state_changed'
extra keys not allowed @ data['id']. Got 1
not a valid value for dictionary value @ data['type']. Got 'subscribe_events'
required key not provided @ data['api_password']. Got None

**Comment by jarno83** [comment]
Same problem with home assistant 0.67.1.

**Comment by nightops** [comment]
After setting up LetsEncrypt, I switched the ssl setting to true for the Control Panel.  This time it gave me the option to automatically connect, or setup manually.  For grins and giggles I chose manual, and then I manually set the URL and password to my local HA install on a RPi3.  Now the URL shows the correct string for the API, including the password.  I can click on the link in Developer Tools and it loads the JSON properly without error.  Unfortunately I now get the following message in Developer Tools Console:
No 'Access-Control-Allow-Origin' header is present on the requested resource.

My configuration.yaml currently has the following:
http:
  base_url: https://ha.XXXXX.com:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret api_password
  cors_allowed_origins:
    - http://hassio.local:7080
    - http://ha.XXXXX.com:7080

I'm not seeing anything that should preclude CORS from allowing the Control Panel access.  I have my router forwarding 80, 443, 8123, and 7080 traffic to my RPi3.  What am I missing?

**Comment by halfbaked** [comment]
Setting up control panel for the first time and seeing the same issue: Password undefined.
I assume the control panel is trying to read the password from somewhere and failing to do so.

Update: Selecting manual in another browser works fine. In fact I wonder if it is because I defined the password, etc. after first trying the control panel, and something was then cached in cookies/browser-db. 

I suggest that the option to manually setup is presented to the user when the control panel fails to connect, and we see the alert:
"Unable to connect to Home Assistant. Please check the Server URL is accessible from this device or change the URL below"

**Comment by nightops** [comment]
Make sure everythjbg is updated.  Then click on the settings in the bottom-right after cancelling the popup.  Manually enter the HA URL and the API password.  Then Save, and X out.  Then reload the page and it should work.

**Comment by frenck** [comment]
If all fails, clear your browser cache.
Make sure you clear the local storage/cookies.

This will give you a fresh start.
